<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit01f1729c40db16a1090cce6fe7d1fc26
{
    public static $prefixesPsr0 = array (
        'O' => 
        array (
            'OAuth\\Unit' => 
            array (
                0 => __DIR__ . '/..' . '/lusitanian/oauth/tests',
            ),
            'OAuth' => 
            array (
                0 => __DIR__ . '/..' . '/lusitanian/oauth/src',
            ),
        ),
    );

    public static $classMap = array (
        'OAuth\\Common\\AutoLoader' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/Common/AutoLoader.php',
        'OAuth\\Common\\Consumer\\Credentials' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/Common/Consumer/Credentials.php',
        'OAuth\\Common\\Consumer\\CredentialsInterface' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/Common/Consumer/CredentialsInterface.php',
        'OAuth\\Common\\Exception\\Exception' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/Common/Exception/Exception.php',
        'OAuth\\Common\\Http\\Client\\AbstractClient' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/Common/Http/Client/AbstractClient.php',
        'OAuth\\Common\\Http\\Client\\ClientInterface' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/Common/Http/Client/ClientInterface.php',
        'OAuth\\Common\\Http\\Client\\CurlClient' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/Common/Http/Client/CurlClient.php',
        'OAuth\\Common\\Http\\Client\\StreamClient' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/Common/Http/Client/StreamClient.php',
        'OAuth\\Common\\Http\\Exception\\TokenResponseException' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/Common/Http/Exception/TokenResponseException.php',
        'OAuth\\Common\\Http\\Uri\\Uri' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/Common/Http/Uri/Uri.php',
        'OAuth\\Common\\Http\\Uri\\UriFactory' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/Common/Http/Uri/UriFactory.php',
        'OAuth\\Common\\Http\\Uri\\UriFactoryInterface' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/Common/Http/Uri/UriFactoryInterface.php',
        'OAuth\\Common\\Http\\Uri\\UriInterface' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/Common/Http/Uri/UriInterface.php',
        'OAuth\\Common\\Service\\AbstractService' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/Common/Service/AbstractService.php',
        'OAuth\\Common\\Service\\ServiceInterface' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/Common/Service/ServiceInterface.php',
        'OAuth\\Common\\Storage\\Exception\\AuthorizationStateNotFoundException' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/Common/Storage/Exception/AuthorizationStateNotFoundException.php',
        'OAuth\\Common\\Storage\\Exception\\StorageException' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/Common/Storage/Exception/StorageException.php',
        'OAuth\\Common\\Storage\\Exception\\TokenNotFoundException' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/Common/Storage/Exception/TokenNotFoundException.php',
        'OAuth\\Common\\Storage\\Memory' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/Common/Storage/Memory.php',
        'OAuth\\Common\\Storage\\Redis' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/Common/Storage/Redis.php',
        'OAuth\\Common\\Storage\\Session' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/Common/Storage/Session.php',
        'OAuth\\Common\\Storage\\SymfonySession' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/Common/Storage/SymfonySession.php',
        'OAuth\\Common\\Storage\\TokenStorageInterface' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/Common/Storage/TokenStorageInterface.php',
        'OAuth\\Common\\Token\\AbstractToken' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/Common/Token/AbstractToken.php',
        'OAuth\\Common\\Token\\Exception\\ExpiredTokenException' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/Common/Token/Exception/ExpiredTokenException.php',
        'OAuth\\Common\\Token\\TokenInterface' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/Common/Token/TokenInterface.php',
        'OAuth\\OAuth1\\Service\\AbstractService' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth1/Service/AbstractService.php',
        'OAuth\\OAuth1\\Service\\BitBucket' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth1/Service/BitBucket.php',
        'OAuth\\OAuth1\\Service\\Etsy' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth1/Service/Etsy.php',
        'OAuth\\OAuth1\\Service\\FitBit' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth1/Service/FitBit.php',
        'OAuth\\OAuth1\\Service\\FiveHundredPx' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth1/Service/FiveHundredPx.php',
        'OAuth\\OAuth1\\Service\\Flickr' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth1/Service/Flickr.php',
        'OAuth\\OAuth1\\Service\\QuickBooks' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth1/Service/QuickBooks.php',
        'OAuth\\OAuth1\\Service\\Redmine' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth1/Service/Redmine.php',
        'OAuth\\OAuth1\\Service\\ScoopIt' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth1/Service/ScoopIt.php',
        'OAuth\\OAuth1\\Service\\ServiceInterface' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth1/Service/ServiceInterface.php',
        'OAuth\\OAuth1\\Service\\Tumblr' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth1/Service/Tumblr.php',
        'OAuth\\OAuth1\\Service\\Twitter' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth1/Service/Twitter.php',
        'OAuth\\OAuth1\\Service\\Xing' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth1/Service/Xing.php',
        'OAuth\\OAuth1\\Service\\Yahoo' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth1/Service/Yahoo.php',
        'OAuth\\OAuth1\\Signature\\Exception\\UnsupportedHashAlgorithmException' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth1/Signature/Exception/UnsupportedHashAlgorithmException.php',
        'OAuth\\OAuth1\\Signature\\Signature' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth1/Signature/Signature.php',
        'OAuth\\OAuth1\\Signature\\SignatureInterface' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth1/Signature/SignatureInterface.php',
        'OAuth\\OAuth1\\Token\\StdOAuth1Token' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth1/Token/StdOAuth1Token.php',
        'OAuth\\OAuth1\\Token\\TokenInterface' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth1/Token/TokenInterface.php',
        'OAuth\\OAuth2\\Service\\AbstractService' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth2/Service/AbstractService.php',
        'OAuth\\OAuth2\\Service\\Amazon' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth2/Service/Amazon.php',
        'OAuth\\OAuth2\\Service\\Bitly' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth2/Service/Bitly.php',
        'OAuth\\OAuth2\\Service\\Box' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth2/Service/Box.php',
        'OAuth\\OAuth2\\Service\\Buffer' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth2/Service/Buffer.php',
        'OAuth\\OAuth2\\Service\\Dailymotion' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth2/Service/Dailymotion.php',
        'OAuth\\OAuth2\\Service\\Delicious' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth2/Service/Delicious.php',
        'OAuth\\OAuth2\\Service\\DeviantArt' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth2/Service/DeviantArt.php',
        'OAuth\\OAuth2\\Service\\Dropbox' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth2/Service/Dropbox.php',
        'OAuth\\OAuth2\\Service\\Exception\\InvalidAccessTypeException' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth2/Service/Exception/InvalidAccessTypeException.php',
        'OAuth\\OAuth2\\Service\\Exception\\InvalidAuthorizationStateException' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth2/Service/Exception/InvalidAuthorizationStateException.php',
        'OAuth\\OAuth2\\Service\\Exception\\InvalidScopeException' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth2/Service/Exception/InvalidScopeException.php',
        'OAuth\\OAuth2\\Service\\Exception\\MissingRefreshTokenException' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth2/Service/Exception/MissingRefreshTokenException.php',
        'OAuth\\OAuth2\\Service\\Facebook' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth2/Service/Facebook.php',
        'OAuth\\OAuth2\\Service\\Foursquare' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth2/Service/Foursquare.php',
        'OAuth\\OAuth2\\Service\\GitHub' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth2/Service/GitHub.php',
        'OAuth\\OAuth2\\Service\\Google' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth2/Service/Google.php',
        'OAuth\\OAuth2\\Service\\Harvest' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth2/Service/Harvest.php',
        'OAuth\\OAuth2\\Service\\Heroku' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth2/Service/Heroku.php',
        'OAuth\\OAuth2\\Service\\Hubic' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth2/Service/Hubic.php',
        'OAuth\\OAuth2\\Service\\Instagram' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth2/Service/Instagram.php',
        'OAuth\\OAuth2\\Service\\JawboneUP' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth2/Service/JawboneUP.php',
        'OAuth\\OAuth2\\Service\\Linkedin' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth2/Service/Linkedin.php',
        'OAuth\\OAuth2\\Service\\Mailchimp' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth2/Service/Mailchimp.php',
        'OAuth\\OAuth2\\Service\\Microsoft' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth2/Service/Microsoft.php',
        'OAuth\\OAuth2\\Service\\Nest' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth2/Service/Nest.php',
        'OAuth\\OAuth2\\Service\\Netatmo' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth2/Service/Netatmo.php',
        'OAuth\\OAuth2\\Service\\ParrotFlowerPower' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth2/Service/ParrotFlowerPower.php',
        'OAuth\\OAuth2\\Service\\Paypal' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth2/Service/Paypal.php',
        'OAuth\\OAuth2\\Service\\Pocket' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth2/Service/Pocket.php',
        'OAuth\\OAuth2\\Service\\Reddit' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth2/Service/Reddit.php',
        'OAuth\\OAuth2\\Service\\RunKeeper' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth2/Service/RunKeeper.php',
        'OAuth\\OAuth2\\Service\\Salesforce' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth2/Service/Salesforce.php',
        'OAuth\\OAuth2\\Service\\ServiceInterface' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth2/Service/ServiceInterface.php',
        'OAuth\\OAuth2\\Service\\SoundCloud' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth2/Service/SoundCloud.php',
        'OAuth\\OAuth2\\Service\\Spotify' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth2/Service/Spotify.php',
        'OAuth\\OAuth2\\Service\\Strava' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth2/Service/Strava.php',
        'OAuth\\OAuth2\\Service\\Ustream' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth2/Service/Ustream.php',
        'OAuth\\OAuth2\\Service\\Vimeo' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth2/Service/Vimeo.php',
        'OAuth\\OAuth2\\Service\\Vkontakte' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth2/Service/Vkontakte.php',
        'OAuth\\OAuth2\\Service\\Yammer' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth2/Service/Yammer.php',
        'OAuth\\OAuth2\\Token\\StdOAuth2Token' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth2/Token/StdOAuth2Token.php',
        'OAuth\\OAuth2\\Token\\TokenInterface' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/OAuth2/Token/TokenInterface.php',
        'OAuth\\ServiceFactory' => __DIR__ . '/..' . '/lusitanian/oauth/src/OAuth/ServiceFactory.php',
        'OAuth\\Unit\\Common\\Consumer\\CredentialsTest' => __DIR__ . '/..' . '/lusitanian/oauth/tests/Unit/Common/Consumer/CredentialsTest.php',
        'OAuth\\Unit\\Common\\Http\\HttpClientsTest' => __DIR__ . '/..' . '/lusitanian/oauth/tests/Unit/Common/Http/HttpClientsTest.php',
        'OAuth\\Unit\\Common\\Storage\\RedisTest' => __DIR__ . '/..' . '/lusitanian/oauth/tests/Unit/Common/Storage/RedisTest.php',
        'OAuth\\Unit\\Common\\Storage\\StorageTest' => __DIR__ . '/..' . '/lusitanian/oauth/tests/Unit/Common/Storage/StorageTest.php',
        'OAuth\\Unit\\Common\\Storage\\SymfonySessionTest' => __DIR__ . '/..' . '/lusitanian/oauth/tests/Unit/Common/Storage/SymfonySessionTest.php',
        'OAuth\\Unit\\ServiceFactoryTest' => __DIR__ . '/..' . '/lusitanian/oauth/tests/Unit/ServiceFactoryTest.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixesPsr0 = ComposerStaticInit01f1729c40db16a1090cce6fe7d1fc26::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit01f1729c40db16a1090cce6fe7d1fc26::$classMap;

        }, null, ClassLoader::class);
    }
}
